config/routes.rb
AmericanLang220::Application.routes.draw do

  get "subscribers/create"
  get "docs/javascript"
  get "docs/curl"
  get "docs/ruby"
  get "docs/java"
  get "docs/python"
  get "docs/php"
  get "communications/transfer"
	
	match "/front", :to=>"pages#front"

	resources :subscribers, :only=>[:create] do
	end
	scope "corporation" do
		resources :ads do
      member do
      get 'crop'
     end

   end
	end

  resources :ads do
    member do
      get 'crop'
    end
  end

  devise_for :users
  devise_for :corporations do
    get '/corporations/sign_out' => 'devise/sessions#destroy'

  end
  resources :betasignups

  resources :robotindex

  match "/developers/", :to=> "robotindex#developers"
  match "/signup/", :to=> "robotindex#gamesignup"
  match "/signup/success", :to=> "robotindex#success"

  match "create", :to => "pages#create"
  match "/success", :to => "pages#success"

  match "/docs", :to => "pages#docs"

  match "/promotion", :to => "advertisersignups#overview"
  match "/channel", :to => "pages#channel"
  match "/contacts", :to => "pages#contact"
  match "/contact", :to => "pages#contact"
  match "/about", :to => "pages#about"
  match "/send", :to => "robotindex#send_mail"
  match "/leader", :to => "pages#leader"
  match "/promotion/partners", :to => "advertisersignups#partner" 

  match "/casters", :to=>"castersignups#overview"
  match "/caster/signup/overview", :to=>"castersignups#overview"
  match "/caster/signup/apply", :to=>"castersignups#apply"
  match "/caster/signup/perks", :to=>"castersignups#perks"
  match "/caster/signup/faq", :to=>"castersignups#faq"
  match "/caster/signup/partners", :to=>"castersignups#partner"
  match "/caster/signup/create", :to=>"castersignups#create"
  
  match "/advertiser/signup/overview", :to=>"advertisersignups#overview"
  match "/advertiser/signup/apply", :to=>"advertisersignups#apply"
  match "/advertiser/signup/demo", :to=>"advertisersignups#demo"
  match "/advertiser/signup/faq", :to=>"advertisersignups#faq"
  match "/advertiser/signup/create", :to=>"advertisersignups#create"
  match "/advertiser/signup/success", :to=>"advertisersignups#success"

  match "/advertiser/signup/overview", :to=>"advertisersignups#overview"
  match "/advertiser/signup/apply", :to=>"advertisersignups#apply"
  match "/advertiser/signup/demo", :to=>"advertisersignups#demo"
  match "/advertiser/signup/faq", :to=>"advertisersignups#faq"
  match "/advertiser/signup/partners", :to=>"advertisersignups#partner"
  match "/advertiser/signup/create", :to=>"advertisersignups#create"

  root :to => "pages#index"

AmericanLang220::Application.routes.draw do
  get "subscribers/create"

  get "docs/javascript"

  get "docs/curl"

  get "docs/ruby"

  get "docs/java"

  get "docs/python"

  get "docs/php"

  match '*a', :to => 'errors#routing'
end

end

app/views/layouts/_corporations_login_item.html.erb
<% if corporation_signed_in? %>

  <%= link_to('Sign out', destroy_corporation_session_path, :method => :delete, :class => 'links') %>
<% else %>

  <%= link_to('Sign in as Corporation', new_corporation_session_path, :class => 'links')  %>
<% end %>

app/views/layouts/_footer.html.erb
      <footer class='footer'>
        <p><a href="/about">About</a> | <a href="/promotion">Advertisers</a> | <a href="/casters">GameCasters</a> | <a href="/promotion/partners">Partners</a> <br>   &copy; Ingidio 2011</p>
      </footer>
<!-- google analytics code -->
<script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-27161201-1']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script>
<!-- end google analytics code -->

app/views/layouts/_login_items.html.erb
<% if user_signed_in? %>
  <%= link_to('Sign out', destroy_user_session_path, :method => :delete, :class => 'links') %>

<% else %>

  <%= link_to('Sign in', new_user_session_path, :class => 'links')  %>

<% end %>

app/views/layouts/_toolbar.html.erb
    <div class="topbar">
      <div class="fill">
        <div class="container">
          <a class="brand" href="/">Ingidio</a>
          <ul class="nav">
            <li class="<%= @toolbar[:home] %>"><a href="/">Home</a></li>
            <li class="<%= @toolbar[:channel] %>"><a href="/channel">Channels</a></li>
            <li class="<%= @toolbar[:leader] %>"><a href="/leader">Leader Board</a></li>
            <li class="<%= @toolbar[:contact] %>"><a href="/contact">Contact</a></li>
          </ul>

          <form action="" class="pull-right">
            <input class="input-small" type="text" placeholder="Username">
            <input class="input-small" type="password" placeholder="Password">
            <button class="btn" type="submit">Sign in</button>
          </form>
        </div>
      </div>
    </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>

  <meta charset="utf-8">
  <title>Ingidio Stream</title>
  <meta name="description" content="">
  <meta name="author" content="">
  <%= stylesheet_link_tag 'bootstrap.css', :media => 'screen' %>
	<%= javascript_include_tag 'jquery-1.6.3.min', 'application' %>
  <%= javascript_include_tag "rails" %>
  <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
  <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
  <![endif]-->
  <!-- Le styles -->

  <%= csrf_meta_tag %>
  <%= yield(:head) %>

  <style type="text/css">
      /* Override some defaults */
      html, body {
        background-color: #000;
	background-image:url("<%= @bg_image %>");
      }
      body {
        padding-top: 40px; /* 40px to make the container go all the way to the bottom of the topbar */
      }
      .container > footer p {
        text-align: center; /* center align it with the container */
      }
      .container {
        width: 820px; /* downsize our container to make the content feel a bit tighter and more cohesive. NOTE: this removes two full columns from the grid, meaning you only go to 14 columns and not 16. */
      }

      /* The white background content wrapper */
      .container > .content {
        background-color: #fff;
        padding: 20px;
        margin: 0 -20px; /* negative indent the amount of the padding to maintain the grid system */
        -webkit-border-radius: 0 0 6px 6px;
           -moz-border-radius: 0 0 6px 6px;
                border-radius: 0 0 6px 6px;
        -webkit-box-shadow: 0 1px 2px rgba(0,0,0,.15);
           -moz-box-shadow: 0 1px 2px rgba(0,0,0,.15);
                box-shadow: 0 1px 2px rgba(0,0,0,.15);
      }

      /* Page header tweaks */
      .page-header {
        background-color: #f5f5f5;
        padding: 20px 20px 10px;
        margin: -20px -20px 20px;
      }

      /* Styles you shouldn't keep as they are for displaying this base example only */
      .content .span10,
      .content .span4 {
        min-height: 500px;
      }
      /* Give a quick and non-cross-browser friendly divider */
      .content .span4 {
        margin-left: 0;
        padding-left: 19px;
        border-left: 1px solid #eee;
      }

      .topbar .btn {
        border: 0;
      }
      .footer {
	background-color:#f5f5f5;
        padding: 5px;
	padding-top:15px;
        margin: 0 0px; /* negative indent the amount of the padding to maintain the grid system */
        -webkit-border-radius: 6px 6px 0px 0px;
        -moz-border-radius: 6px 6px 0px 0px;
        border-radius: 6px 6px 0px 0px;
        -webkit-box-shadow: 0 1px 2px rgba(0,0,0,.15);
        -moz-box-shadow: 0 1px 2px rgba(0,0,0,.15);
        box-shadow: 0 1px 2px rgba(0,0,0,.15);
      }
      .error_form {
        font-color: #000;
        padding-left: 5px;
        border: 1px solid #FF6600;
      }
      .error_form p {
        padding: 0px;
        font-size: 100%;
        color: #FF6600;
      }
  </style>

  <!--<link rel="shortcut icon" href="images/favicon.ico">-->
  </head>
</head>
<body>

<%= yield %>

</body>
</html>